### ISSUE TITLE
Chrome hardwired hotkeys are enabled

### ISSUE THREAD

**Issue by Armaldio** [Armaldio/c3-desktop#4]
pressing CTRL+W close a window

**Comment by Armaldio** [comment]
Which window ?

Ctrl+W doesn't close the main window for me

**Comment by mitsuhashish** [comment]
> Which window ?
> 
> Ctrl+W doesn't close the main window for me

On preview window

**Comment by Armaldio** [comment]
Oh, Ok
So what is the desired behavior (global, not just for Ctrl+W)

**Comment by mitsuhashish** [comment]
To disable the chrome's default hotkey that interfere with the window itself (note, this doesn't include ie f11 to go fullscreen)

**Comment by Armaldio** [comment]
I don't really see the point of this after thinking about it
After all, C3's default behaviour doesn't prevent native shortcuts

Unless you have a valid use case, i'm closing this
